# Generated by Django 3.2 on 2022-05-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220508_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerContact',
            new_name='Contact',
        ),
    ]
