# Generated by Django 3.2 on 2022-04-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='blurb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sku',
        ),
    ]
